name: ControlFront Scan
permissions:
  actions: write
  contents: read
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://cf-dev-x8a9k2h1r7v3pzq5.ngrok.app
          CF_ORG_ID: e19204a5-736a-466c-8242-6c4b1e1c7943
          CF_PROJECT_ID: addb0d66-7fbe-4d0d-8645-dd00fd8f4da4
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: DMWt8f9mLLbK8ghUPbk5-2Hlpt62phMdpkMSwrw0PuI