name: ControlFront Scan
permissions:
  actions: write
  contents: read
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/controlfront.yml"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - ".github/workflows/controlfront.yml"
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://app.controlfront.io
          CF_ORG_ID: c6c6cdfa-15bb-4233-98d1-501a6c134da0
          CF_PROJECT_ID: 96c66ca9-726c-4368-97df-0649d2fc065a
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: xbqak74Y-9HtTsh_0QI3DnYLAreDQNQkdkO7ZtsMyS4