name: ControlFront Scan
permissions:
  actions: write
  contents: read
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://app.controlfront.io
          CF_ORG_ID: 446b215d-09c3-4d4f-9217-903d5bd7e8ca
          CF_PROJECT_ID: 7ac40ea6-be2f-4b36-b90a-192a4062d045
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: nXUrSGwgtjHLv9Q7v24dQKVRu9AnBoz9vhyGX_mJZOE